# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Taller Imputación de Datos
subtitle: Un enfoque práctico con Python
description: Un libro interactivo para aprender técnicas de imputación de datos utilizando Python.
author: José Manuel Menco Galván
university: Universidad del Norte
institution: Departamento de Ciencias Básicas
copyright: "2024, José Manuel Menco Galván"
language: es
theme:
  name: sphinx_book_theme
logo: logoUN.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extensions:
    - sphinxcontrib.bibtex

# Information about where the book exists on the web
repository:
  url: https://github.com/LasciaStare/Taller-Imputacion  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
